---
-   hosts: solr
    gather_facts: True         
    vars:
      dir_code_src: '~/code/'
      dir_solr_data: '/opt/solr/data'
      dir_tarball: '/opt/indexes/'
      # replace colons, scp doesn't play well with colons
      datetime: "{{ ansible_date_time.date }}-{{ ansible_date_time.time | regex_replace(':','_') }}"
      email_to: "{{ lookup('env', 'EMAIL_SYS_ADMINS') }}"
      server_roles:
        - production
        - stage
        - dev
      s3_bucket: solr.ucldc
      s3_root_path: "indexes/{{ server_role }}"
      region: us-west-2
      remote_user: ec2-user
      s3_file_path: "s3://{{ s3_bucket }}/{{s3_root_path}}/{{ ansible_date_time.year }}/{{ ansible_date_time.month }}/solr-index.{{ datetime }}.tar.bz2"
    tasks:
    - debug: var=ansible_date_time.date
    - debug: var=ansible_date_time.time
    - debug: var=datetime
    - fail: msg="Define server_role to one of production, stage or dev"
      when: server_role not in  server_roles
    - name: create tarball target directory
      become: yes
      file:
        path: "{{ dir_tarball }}"
        state: directory
        mode: 0777
    - name: tar up latest solr index directoy
      command: tar --force-local -cvf "{{ dir_tarball }}/solr-index.{{ datetime }}.tar" index/
      args:
        chdir: "{{ dir_solr_data }}"
        warn: no
    - name: bzip index file
      command: bzip2 "{{ dir_tarball }}/solr-index.{{ datetime }}.tar"
      args:
        warn: no
    - name: push index tarball to s3 for server_role
      shell: aws --region="{{ region }}" s3 cp "{{ dir_tarball }}/solr-index.{{ datetime}}.tar.bz2" "{{ s3_file_path }}"
###    - name: push index tarball to s3 for server_role to the latest bucket
###      shell: aws s3 cp --region={{ region }} {{ dir_tarball }}/solr-index.{{ datetime}}.tar.bz2 s3://{{ s3_bucket }}/{{ s3_root_path }}/solr-index.tar.bz2
### NOTE: s3 module not working, gets a connection reset by peer
###      s3:
###        bucket: "{{ s3_bucket }}"
###        mode: put
###        src: solr-index.{{ datetime }}.tar.bz2
###        object: solr-index.{{ datetime }}.tar.bz2
###        #metadata: 'Content-Encoding=bzip2'
###        #        ###    - name: fetch index tarball
###        #                ###fetch: src=solr-index.{{ datetime }}.tar.bz2
###        #                        ###     dest=/var/local/solr-indexes/ flat=yes
###        #                          
    - name: remove artifacts on remote
      file:
        state: absent
        path: "{{ dir_tarball }}/solr-index.{{ datetime }}.tar.bz2"
    - debug: var=s3_file_path
###    - name: email note of new index (right now only manual index overwrite)-
###      local_action: mail
###                    from="ucldc@example.edu"
###                    to={{ email_to }}
###                    subject="New solr index tarball ready"
###                    body="New solr index ready for download-> /var/local/solr-indexes/solr-index.{{datetime}}.tar.bz2"
